<?xml version="1.0" encoding="utf-8"?><!DOCTYPE subject [<!--    -->
    <!ELEMENT subject (text,lesson*)>
    <!ELEMENT text  (#PCDATA)>
    <!ELEMENT lesson (text, question*)>
    <!ELEMENT answer (#PCDATA)>
    <!ELEMENT question (text,answer*)>
    <!ATTLIST answer
        isCorrect (true|false) #REQUIRED
        >

    ]>
<subject>
    <text> testfach</text>
    <lesson>
        <text>lesson 1</text>
        <question>
            <text>
                5*5=?
            </text>
            <answer isCorrect="true">
                25
            </answer>
            <answer isCorrect="false">
                5
            </answer>
            <answer isCorrect="false">
                -10
            </answer>
        </question>
    </lesson>
    <lesson>
        <text>lesson 2</text>
        <question>
            <text>4!</text>
            <answer isCorrect="true">24</answer>
            <answer isCorrect="false">6</answer>
            <answer isCorrect="false">1243</answer>
        </question>
    </lesson>
    <lesson>
        <text>lesson -1</text>
        <question>
            <text>bdhiviuer</text>
            <answer isCorrect="false">ew</answer>
            <answer isCorrect="true">-1</answer>
        </question>
    </lesson>
</subject>