<?xml version="1.0" encoding="utf-8"?><!DOCTYPE subject [<!--    -->
    <!ELEMENT subject (text, lesson)>
    <!ELEMENT text  (#PCDATA)><!ELEMENT lesson (text, question*)>

    <!ELEMENT answer (#PCDATA)><!ELEMENT question (text,answer*)>
    <!ATTLIST answer
        isCorrect (true|false) #REQUIRED
        >
    ]>
<subject>
    <text>tt</text>
    <lesson>
        <text>Bla Bla</text>
        <question>
            <text>
                5*5=?
            </text>
            <answer isCorrect="true">
                25
            </answer>
            <answer isCorrect="false">
                5
            </answer>
            <answer isCorrect="false">
                -10
            </answer>
        </question>
    </lesson>
</subject>