=== lucth98/LearningApp/LearningApp/app/src/main/assets/LearnigFiles/subject.dtd
<!ELEMENT subject (text,lesson*)>
    <!ELEMENT text  (#PCDATA)>
    <!ELEMENT lesson (text, question*)>
    <!ELEMENT answer (#PCDATA)>
    <!ELEMENT question (text,answer*)>
    <!ATTLIST answer
        isCorrect (true|false) #REQUIRED
        >
    <!ATTLIST subject
        Name   CDATA #REQUIRED>
    <!ATTLIST lesson
        Name   CDATA #REQUIRED
        finished (true|false) #REQUIRED>
    <!ATTLIST question
        Name   CDATA #REQUIRED
        finished (true|false) #REQUIRED
        >

=== lucth98/LearningApp/LearningApp/app/src/main/assets/LearnigFiles/testlearning2.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE subject SYSTEM "subject.dtd">
<subject Name="Test">
    <text> testfach</text>
    <lesson Name="lesson 1" finished="false" endtime="">
        <text>lesson 1 esfewf</text>
        <question Name="Question 1" finished="false" >
            <text>
                5*5=?
            </text>
            <answer isCorrect="true">
                25
            </answer>
            <answer isCorrect="false">
                5
            </answer>
            <answer isCorrect="false">
                -10
            </answer>
        </question>
    </lesson>
    <lesson Name="lesson 2" finished="false" endtime="">
        <text>lesson 2  sdfkueggkuzfugzeizl</text>
        <question Name="Frage 1" finished="false">
            <text>4!</text>
            <answer isCorrect="true">24</answer>
            <answer isCorrect="false">6</answer>
            <answer isCorrect="false">1243</answer>
        </question>
    </lesson>
    <lesson Name="Lesson 3" finished="false" endtime="">
        <text>lesson -1 sfgiuewiluh efwilugilzif iuuggiu f
        </text>
        <question Name="bhbhdd" finished="false">
            <text>bdhiviuer</text>
            <answer isCorrect="false">ew</answer>
            <answer isCorrect="true">-1</answer>
        </question>
    </lesson>
</subject>

=== lucth98/LearningApp/LearningApp/app/src/main/assets/LearnigFiles/testlearning.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE subject SYSTEM "subject.dtd">
<subject Name="Test Fach">
    <text>tt</text>
    <lesson Name="lesson 1" finished="false" endtime="" Image="Fragezeichen.jpg">
        <text>test file
            Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
            invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam
            et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem
            ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
            eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos
            et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus
            est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam
            nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero
            eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus
            est Lorem ipsum dolor sit amet.
        </text>
        <question Name=" frage 1" finished="false">
            <text>
                5*5=?
            </text>
            <answer isCorrect="true">
                25
            </answer>
            <answer isCorrect="false">
                5
            </answer>
            <answer isCorrect="false">
                -10
            </answer>
        </question>
        <question Name="2 frage" finished="false">
            <text>
                5*2=?
            </text>
            <answer isCorrect="true">
                10
            </answer>
            <answer isCorrect="false">
                5
            </answer>
            <answer isCorrect="false">
                -10
            </answer>
        </question>
    </lesson>
    <lesson Name="lesson 2" finished="false" endtime="">
        <text>test file lesson 2 </text>
        <question Name="Question 1" finished="false" >
            <text>
                5*5=?
            </text>
            <answer isCorrect="true">
                25
            </answer>
            <answer isCorrect="false">
                5
            </answer>
            <answer isCorrect="false">
                -10
            </answer>
        </question>
    </lesson>
    <lesson Name="lesson 3" finished="false" endtime="">
        <text>test file lesson 3  </text>
        <question Name="Frage 1" finished="false">
            <text>4!</text>
            <answer isCorrect="true">24</answer>
            <answer isCorrect="false">6</answer>
            <answer isCorrect="false">1243</answer>
        </question>
    </lesson>
    <lesson Name="Lesson 4" finished="false" endtime="">
        <text>test file
            lesson 4
        </text>
        <question Name="test multiple answers" finished="false">
            <text>right awnser 2 4 6</text>
            <answer isCorrect="false">1</answer>
            <answer isCorrect="true">2</answer>
            <answer isCorrect="false">3</answer>
            <answer isCorrect="true">4</answer>
            <answer isCorrect="false">5</answer>
            <answer isCorrect="true">6</answer>
        </question>
    </lesson>
</subject>
